parameters:
  kapitan:
    compile:
      - input_paths:
          - openshift-prometheus-proxy/component/app.jsonnet
        input_type: jsonnet
        output_path: apps/
      - input_paths:
          - openshift-prometheus-proxy/component/main.jsonnet
        input_type: jsonnet
        output_path: openshift-prometheus-proxy/
