parameters:
  kapitan:
    dependencies:
      - type: https
        source: https://raw.githubusercontent.com/appuio/openshift-prometheus-proxy/${openshift_prometheus_proxy:version}/template/openshift-prometheus-proxy.yaml
        output_path: dependencies/openshift-prometheus-proxy/manifests/${openshift_prometheus_proxy:version}/template.yaml
    compile:
      - input_paths:
          - openshift-prometheus-proxy/component/app.jsonnet
        input_type: jsonnet
        output_path: apps/
      - input_paths:
          - openshift-prometheus-proxy/component/main.jsonnet
        input_type: jsonnet
        output_path: openshift-prometheus-proxy/
